{
  "comments": [
    {
      "key": {
        "uuid": "9a561d44_c3d93985",
        "filename": "openflow-protocol-impl/src/test/java/org/opendaylight/openflowjava/protocol/impl/core/connection/OutboundQueueEntryTest.java",
        "patchSetId": 3
      },
      "lineNbr": 131,
      "author": {
        "id": 664
      },
      "writtenOn": "2016-06-28T11:58:29Z",
      "side": 1,
      "message": "if we want to test immediate failure on second entry.commit(), we can\u0027t call entry.fail() again - as it definitely calls failure on passed callback\n\nplease remove the second entry.fail() call",
      "range": {
        "startLine": 131,
        "startChar": 8,
        "endLine": 131,
        "endChar": 38
      },
      "revId": "91da96bfd0ff820b2d19aeefc6348f43a92e6b51",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a561d44_96993d71",
        "filename": "openflow-protocol-impl/src/test/java/org/opendaylight/openflowjava/protocol/impl/core/connection/OutboundQueueEntryTest.java",
        "patchSetId": 3
      },
      "lineNbr": 131,
      "author": {
        "id": 5280
      },
      "writtenOn": "2016-06-28T13:29:40Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "9a561d44_c3d93985",
      "range": {
        "startLine": 131,
        "startChar": 8,
        "endLine": 131,
        "endChar": 38
      },
      "revId": "91da96bfd0ff820b2d19aeefc6348f43a92e6b51",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81",
      "unresolved": false
    }
  ]
}